// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domains/person/person.proto

package com.thougtworks.domains.person;

public final class PersonOuterClass {
  private PersonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_domains_person_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_domains_person_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033domains/person/person.proto\022\016domains.p" +
      "erson\032!domains/person/phone_number.proto" +
      "\"\216\001\n\006Person\022\n\n\002id\030\001 \001(\005\022\022\n\nfirst_name\030\002 " +
      "\001(\t\022\021\n\tlast_name\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\0222\n" +
      "\rphone_numbers\030\005 \003(\0132\033.domains.person.Ph" +
      "oneNumber\022\016\n\006active\030\006 \001(\010B\"\n\036com.thougtw" +
      "orks.domains.personP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.thougtworks.domains.person.PhoneNumberOuterClass.getDescriptor(),
        });
    internal_static_domains_person_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_domains_person_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_domains_person_Person_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Email", "PhoneNumbers", "Active", });
    com.thougtworks.domains.person.PhoneNumberOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
