// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domains/person/person_response.proto

package com.thougtworks.domains.person;

public interface PersonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:domains.person.PersonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.domains.person.Person person = 1;</code>
   * @return Whether the person field is set.
   */
  boolean hasPerson();
  /**
   * <code>.domains.person.Person person = 1;</code>
   * @return The person.
   */
  com.thougtworks.domains.person.Person getPerson();
  /**
   * <code>.domains.person.Person person = 1;</code>
   */
  com.thougtworks.domains.person.PersonOrBuilder getPersonOrBuilder();

  /**
   * <code>.domains.common.Error error = 2;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.domains.common.Error error = 2;</code>
   * @return The error.
   */
  com.thougtworks.domains.common.Error getError();
  /**
   * <code>.domains.common.Error error = 2;</code>
   */
  com.thougtworks.domains.common.ErrorOrBuilder getErrorOrBuilder();

  public com.thougtworks.domains.person.PersonResponse.ResultCase getResultCase();
}
