// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domains/person/person_request.proto

package com.thougtworks.domains.person;

public interface PersonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:domains.person.PersonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
