// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domains/person/phone_type.proto

package com.thougtworks.domains.person;

public final class PhoneTypeOuterClass {
  private PhoneTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037domains/person/phone_type.proto\022\016domai" +
      "ns.person*+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004WO" +
      "RK\020\001\022\010\n\004HOME\020\002B\"\n\036com.thougtworks.domain" +
      "s.personP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
