// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domains/person/phone_number.proto

package com.thougtworks.domains.person;

public final class PhoneNumberOuterClass {
  private PhoneNumberOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_domains_person_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_domains_person_PhoneNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!domains/person/phone_number.proto\022\016dom" +
      "ains.person\032\037domains/person/phone_type.p" +
      "roto\"L\n\013PhoneNumber\022-\n\nphone_type\030\001 \001(\0162" +
      "\031.domains.person.PhoneType\022\016\n\006number\030\002 \001" +
      "(\tB\"\n\036com.thougtworks.domains.personP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.thougtworks.domains.person.PhoneTypeOuterClass.getDescriptor(),
        });
    internal_static_domains_person_PhoneNumber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_domains_person_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_domains_person_PhoneNumber_descriptor,
        new java.lang.String[] { "PhoneType", "Number", });
    com.thougtworks.domains.person.PhoneTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
