// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domains/person/phone_number.proto

package com.thougtworks.domains.person;

public interface PhoneNumberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:domains.person.PhoneNumber)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.domains.person.PhoneType phone_type = 1;</code>
   * @return The enum numeric value on the wire for phoneType.
   */
  int getPhoneTypeValue();
  /**
   * <code>.domains.person.PhoneType phone_type = 1;</code>
   * @return The phoneType.
   */
  com.thougtworks.domains.person.PhoneType getPhoneType();

  /**
   * <code>string number = 2;</code>
   * @return The number.
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 2;</code>
   * @return The bytes for number.
   */
  com.google.protobuf.ByteString
      getNumberBytes();
}
