// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domains/person/person.proto

package com.kroger.domains.person;

public final class PersonOuterClass {
  private PersonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:domains.person.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string last_name = 3;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string last_name = 3;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
     */
    java.util.List<com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber> 
        getPhoneNumbersList();
    /**
     * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
     */
    com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber getPhoneNumbers(int index);
    /**
     * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
     */
    int getPhoneNumbersCount();
    /**
     * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
     */
    java.util.List<? extends com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumberOrBuilder> 
        getPhoneNumbersOrBuilderList();
    /**
     * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
     */
    com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumberOrBuilder getPhoneNumbersOrBuilder(
        int index);

    /**
     * <code>bool active = 6;</code>
     * @return The active.
     */
    boolean getActive();
  }
  /**
   * Protobuf type {@code domains.person.Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:domains.person.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      firstName_ = "";
      lastName_ = "";
      email_ = "";
      phoneNumbers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                phoneNumbers_ = new java.util.ArrayList<com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber>();
                mutable_bitField0_ |= 0x00000001;
              }
              phoneNumbers_.add(
                  input.readMessage(com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.parser(), extensionRegistry));
              break;
            }
            case 48: {

              active_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          phoneNumbers_ = java.util.Collections.unmodifiableList(phoneNumbers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kroger.domains.person.PersonOuterClass.internal_static_domains_person_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kroger.domains.person.PersonOuterClass.internal_static_domains_person_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kroger.domains.person.PersonOuterClass.Person.class, com.kroger.domains.person.PersonOuterClass.Person.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int FIRST_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string last_name = 3;</code>
     * @return The lastName.
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string last_name = 3;</code>
     * @return The bytes for lastName.
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_NUMBERS_FIELD_NUMBER = 5;
    private java.util.List<com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber> phoneNumbers_;
    /**
     * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
     */
    public java.util.List<com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber> getPhoneNumbersList() {
      return phoneNumbers_;
    }
    /**
     * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
     */
    public java.util.List<? extends com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumberOrBuilder> 
        getPhoneNumbersOrBuilderList() {
      return phoneNumbers_;
    }
    /**
     * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
     */
    public int getPhoneNumbersCount() {
      return phoneNumbers_.size();
    }
    /**
     * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
     */
    public com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber getPhoneNumbers(int index) {
      return phoneNumbers_.get(index);
    }
    /**
     * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
     */
    public com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumberOrBuilder getPhoneNumbersOrBuilder(
        int index) {
      return phoneNumbers_.get(index);
    }

    public static final int ACTIVE_FIELD_NUMBER = 6;
    private boolean active_;
    /**
     * <code>bool active = 6;</code>
     * @return The active.
     */
    public boolean getActive() {
      return active_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
      }
      for (int i = 0; i < phoneNumbers_.size(); i++) {
        output.writeMessage(5, phoneNumbers_.get(i));
      }
      if (active_ != false) {
        output.writeBool(6, active_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
      }
      for (int i = 0; i < phoneNumbers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, phoneNumbers_.get(i));
      }
      if (active_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, active_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kroger.domains.person.PersonOuterClass.Person)) {
        return super.equals(obj);
      }
      com.kroger.domains.person.PersonOuterClass.Person other = (com.kroger.domains.person.PersonOuterClass.Person) obj;

      if (getId()
          != other.getId()) return false;
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getPhoneNumbersList()
          .equals(other.getPhoneNumbersList())) return false;
      if (getActive()
          != other.getActive()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (getPhoneNumbersCount() > 0) {
        hash = (37 * hash) + PHONE_NUMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getPhoneNumbersList().hashCode();
      }
      hash = (37 * hash) + ACTIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getActive());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kroger.domains.person.PersonOuterClass.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kroger.domains.person.PersonOuterClass.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kroger.domains.person.PersonOuterClass.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kroger.domains.person.PersonOuterClass.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kroger.domains.person.PersonOuterClass.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kroger.domains.person.PersonOuterClass.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kroger.domains.person.PersonOuterClass.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kroger.domains.person.PersonOuterClass.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kroger.domains.person.PersonOuterClass.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kroger.domains.person.PersonOuterClass.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kroger.domains.person.PersonOuterClass.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kroger.domains.person.PersonOuterClass.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kroger.domains.person.PersonOuterClass.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code domains.person.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:domains.person.Person)
        com.kroger.domains.person.PersonOuterClass.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kroger.domains.person.PersonOuterClass.internal_static_domains_person_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kroger.domains.person.PersonOuterClass.internal_static_domains_person_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kroger.domains.person.PersonOuterClass.Person.class, com.kroger.domains.person.PersonOuterClass.Person.Builder.class);
      }

      // Construct using com.kroger.domains.person.PersonOuterClass.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPhoneNumbersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        firstName_ = "";

        lastName_ = "";

        email_ = "";

        if (phoneNumbersBuilder_ == null) {
          phoneNumbers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          phoneNumbersBuilder_.clear();
        }
        active_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kroger.domains.person.PersonOuterClass.internal_static_domains_person_Person_descriptor;
      }

      @java.lang.Override
      public com.kroger.domains.person.PersonOuterClass.Person getDefaultInstanceForType() {
        return com.kroger.domains.person.PersonOuterClass.Person.getDefaultInstance();
      }

      @java.lang.Override
      public com.kroger.domains.person.PersonOuterClass.Person build() {
        com.kroger.domains.person.PersonOuterClass.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kroger.domains.person.PersonOuterClass.Person buildPartial() {
        com.kroger.domains.person.PersonOuterClass.Person result = new com.kroger.domains.person.PersonOuterClass.Person(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.email_ = email_;
        if (phoneNumbersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            phoneNumbers_ = java.util.Collections.unmodifiableList(phoneNumbers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.phoneNumbers_ = phoneNumbers_;
        } else {
          result.phoneNumbers_ = phoneNumbersBuilder_.build();
        }
        result.active_ = active_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kroger.domains.person.PersonOuterClass.Person) {
          return mergeFrom((com.kroger.domains.person.PersonOuterClass.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kroger.domains.person.PersonOuterClass.Person other) {
        if (other == com.kroger.domains.person.PersonOuterClass.Person.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (phoneNumbersBuilder_ == null) {
          if (!other.phoneNumbers_.isEmpty()) {
            if (phoneNumbers_.isEmpty()) {
              phoneNumbers_ = other.phoneNumbers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePhoneNumbersIsMutable();
              phoneNumbers_.addAll(other.phoneNumbers_);
            }
            onChanged();
          }
        } else {
          if (!other.phoneNumbers_.isEmpty()) {
            if (phoneNumbersBuilder_.isEmpty()) {
              phoneNumbersBuilder_.dispose();
              phoneNumbersBuilder_ = null;
              phoneNumbers_ = other.phoneNumbers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              phoneNumbersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPhoneNumbersFieldBuilder() : null;
            } else {
              phoneNumbersBuilder_.addAllMessages(other.phoneNumbers_);
            }
          }
        }
        if (other.getActive() != false) {
          setActive(other.getActive());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kroger.domains.person.PersonOuterClass.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kroger.domains.person.PersonOuterClass.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string first_name = 2;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string first_name = 2;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string first_name = 2;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 2;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string last_name = 3;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string last_name = 3;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string last_name = 3;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 3;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 4;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber> phoneNumbers_ =
        java.util.Collections.emptyList();
      private void ensurePhoneNumbersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          phoneNumbers_ = new java.util.ArrayList<com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber>(phoneNumbers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber, com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.Builder, com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumberOrBuilder> phoneNumbersBuilder_;

      /**
       * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
       */
      public java.util.List<com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber> getPhoneNumbersList() {
        if (phoneNumbersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phoneNumbers_);
        } else {
          return phoneNumbersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
       */
      public int getPhoneNumbersCount() {
        if (phoneNumbersBuilder_ == null) {
          return phoneNumbers_.size();
        } else {
          return phoneNumbersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
       */
      public com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber getPhoneNumbers(int index) {
        if (phoneNumbersBuilder_ == null) {
          return phoneNumbers_.get(index);
        } else {
          return phoneNumbersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
       */
      public Builder setPhoneNumbers(
          int index, com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber value) {
        if (phoneNumbersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneNumbersIsMutable();
          phoneNumbers_.set(index, value);
          onChanged();
        } else {
          phoneNumbersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
       */
      public Builder setPhoneNumbers(
          int index, com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.Builder builderForValue) {
        if (phoneNumbersBuilder_ == null) {
          ensurePhoneNumbersIsMutable();
          phoneNumbers_.set(index, builderForValue.build());
          onChanged();
        } else {
          phoneNumbersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
       */
      public Builder addPhoneNumbers(com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber value) {
        if (phoneNumbersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneNumbersIsMutable();
          phoneNumbers_.add(value);
          onChanged();
        } else {
          phoneNumbersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
       */
      public Builder addPhoneNumbers(
          int index, com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber value) {
        if (phoneNumbersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneNumbersIsMutable();
          phoneNumbers_.add(index, value);
          onChanged();
        } else {
          phoneNumbersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
       */
      public Builder addPhoneNumbers(
          com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.Builder builderForValue) {
        if (phoneNumbersBuilder_ == null) {
          ensurePhoneNumbersIsMutable();
          phoneNumbers_.add(builderForValue.build());
          onChanged();
        } else {
          phoneNumbersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
       */
      public Builder addPhoneNumbers(
          int index, com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.Builder builderForValue) {
        if (phoneNumbersBuilder_ == null) {
          ensurePhoneNumbersIsMutable();
          phoneNumbers_.add(index, builderForValue.build());
          onChanged();
        } else {
          phoneNumbersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
       */
      public Builder addAllPhoneNumbers(
          java.lang.Iterable<? extends com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber> values) {
        if (phoneNumbersBuilder_ == null) {
          ensurePhoneNumbersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, phoneNumbers_);
          onChanged();
        } else {
          phoneNumbersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
       */
      public Builder clearPhoneNumbers() {
        if (phoneNumbersBuilder_ == null) {
          phoneNumbers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          phoneNumbersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
       */
      public Builder removePhoneNumbers(int index) {
        if (phoneNumbersBuilder_ == null) {
          ensurePhoneNumbersIsMutable();
          phoneNumbers_.remove(index);
          onChanged();
        } else {
          phoneNumbersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
       */
      public com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.Builder getPhoneNumbersBuilder(
          int index) {
        return getPhoneNumbersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
       */
      public com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumberOrBuilder getPhoneNumbersOrBuilder(
          int index) {
        if (phoneNumbersBuilder_ == null) {
          return phoneNumbers_.get(index);  } else {
          return phoneNumbersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
       */
      public java.util.List<? extends com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumberOrBuilder> 
           getPhoneNumbersOrBuilderList() {
        if (phoneNumbersBuilder_ != null) {
          return phoneNumbersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phoneNumbers_);
        }
      }
      /**
       * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
       */
      public com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.Builder addPhoneNumbersBuilder() {
        return getPhoneNumbersFieldBuilder().addBuilder(
            com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.getDefaultInstance());
      }
      /**
       * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
       */
      public com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.Builder addPhoneNumbersBuilder(
          int index) {
        return getPhoneNumbersFieldBuilder().addBuilder(
            index, com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.getDefaultInstance());
      }
      /**
       * <code>repeated .domains.person.PhoneNumber phone_numbers = 5;</code>
       */
      public java.util.List<com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.Builder> 
           getPhoneNumbersBuilderList() {
        return getPhoneNumbersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber, com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.Builder, com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumberOrBuilder> 
          getPhoneNumbersFieldBuilder() {
        if (phoneNumbersBuilder_ == null) {
          phoneNumbersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber, com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.Builder, com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumberOrBuilder>(
                  phoneNumbers_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          phoneNumbers_ = null;
        }
        return phoneNumbersBuilder_;
      }

      private boolean active_ ;
      /**
       * <code>bool active = 6;</code>
       * @return The active.
       */
      public boolean getActive() {
        return active_;
      }
      /**
       * <code>bool active = 6;</code>
       * @param value The active to set.
       * @return This builder for chaining.
       */
      public Builder setActive(boolean value) {
        
        active_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool active = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearActive() {
        
        active_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:domains.person.Person)
    }

    // @@protoc_insertion_point(class_scope:domains.person.Person)
    private static final com.kroger.domains.person.PersonOuterClass.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kroger.domains.person.PersonOuterClass.Person();
    }

    public static com.kroger.domains.person.PersonOuterClass.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kroger.domains.person.PersonOuterClass.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_domains_person_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_domains_person_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033domains/person/person.proto\022\016domains.p" +
      "erson\032!domains/person/phone_number.proto" +
      "\"\216\001\n\006Person\022\n\n\002id\030\001 \001(\005\022\022\n\nfirst_name\030\002 " +
      "\001(\t\022\021\n\tlast_name\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\0222\n" +
      "\rphone_numbers\030\005 \003(\0132\033.domains.person.Ph" +
      "oneNumber\022\016\n\006active\030\006 \001(\010B\033\n\031com.kroger." +
      "domains.personb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kroger.domains.person.PhoneNumberOuterClass.getDescriptor(),
        });
    internal_static_domains_person_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_domains_person_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_domains_person_Person_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Email", "PhoneNumbers", "Active", });
    com.kroger.domains.person.PhoneNumberOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
