// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domains/person/person_response.proto

package com.kroger.domains.person;

public final class PersonResponseOuterClass {
  private PersonResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:domains.person.PersonResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.domains.person.Person person = 1;</code>
     * @return Whether the person field is set.
     */
    boolean hasPerson();
    /**
     * <code>.domains.person.Person person = 1;</code>
     * @return The person.
     */
    com.kroger.domains.person.PersonOuterClass.Person getPerson();
    /**
     * <code>.domains.person.Person person = 1;</code>
     */
    com.kroger.domains.person.PersonOuterClass.PersonOrBuilder getPersonOrBuilder();

    /**
     * <code>.domains.common.Error error = 2;</code>
     * @return Whether the error field is set.
     */
    boolean hasError();
    /**
     * <code>.domains.common.Error error = 2;</code>
     * @return The error.
     */
    com.kroger.domains.common.ErrorOuterClass.Error getError();
    /**
     * <code>.domains.common.Error error = 2;</code>
     */
    com.kroger.domains.common.ErrorOuterClass.ErrorOrBuilder getErrorOrBuilder();

    public com.kroger.domains.person.PersonResponseOuterClass.PersonResponse.ResultCase getResultCase();
  }
  /**
   * Protobuf type {@code domains.person.PersonResponse}
   */
  public  static final class PersonResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:domains.person.PersonResponse)
      PersonResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PersonResponse.newBuilder() to construct.
    private PersonResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PersonResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PersonResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PersonResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.kroger.domains.person.PersonOuterClass.Person.Builder subBuilder = null;
              if (resultCase_ == 1) {
                subBuilder = ((com.kroger.domains.person.PersonOuterClass.Person) result_).toBuilder();
              }
              result_ =
                  input.readMessage(com.kroger.domains.person.PersonOuterClass.Person.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.kroger.domains.person.PersonOuterClass.Person) result_);
                result_ = subBuilder.buildPartial();
              }
              resultCase_ = 1;
              break;
            }
            case 18: {
              com.kroger.domains.common.ErrorOuterClass.Error.Builder subBuilder = null;
              if (resultCase_ == 2) {
                subBuilder = ((com.kroger.domains.common.ErrorOuterClass.Error) result_).toBuilder();
              }
              result_ =
                  input.readMessage(com.kroger.domains.common.ErrorOuterClass.Error.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.kroger.domains.common.ErrorOuterClass.Error) result_);
                result_ = subBuilder.buildPartial();
              }
              resultCase_ = 2;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kroger.domains.person.PersonResponseOuterClass.internal_static_domains_person_PersonResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kroger.domains.person.PersonResponseOuterClass.internal_static_domains_person_PersonResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kroger.domains.person.PersonResponseOuterClass.PersonResponse.class, com.kroger.domains.person.PersonResponseOuterClass.PersonResponse.Builder.class);
    }

    private int resultCase_ = 0;
    private java.lang.Object result_;
    public enum ResultCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      PERSON(1),
      ERROR(2),
      RESULT_NOT_SET(0);
      private final int value;
      private ResultCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ResultCase valueOf(int value) {
        return forNumber(value);
      }

      public static ResultCase forNumber(int value) {
        switch (value) {
          case 1: return PERSON;
          case 2: return ERROR;
          case 0: return RESULT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ResultCase
    getResultCase() {
      return ResultCase.forNumber(
          resultCase_);
    }

    public static final int PERSON_FIELD_NUMBER = 1;
    /**
     * <code>.domains.person.Person person = 1;</code>
     * @return Whether the person field is set.
     */
    public boolean hasPerson() {
      return resultCase_ == 1;
    }
    /**
     * <code>.domains.person.Person person = 1;</code>
     * @return The person.
     */
    public com.kroger.domains.person.PersonOuterClass.Person getPerson() {
      if (resultCase_ == 1) {
         return (com.kroger.domains.person.PersonOuterClass.Person) result_;
      }
      return com.kroger.domains.person.PersonOuterClass.Person.getDefaultInstance();
    }
    /**
     * <code>.domains.person.Person person = 1;</code>
     */
    public com.kroger.domains.person.PersonOuterClass.PersonOrBuilder getPersonOrBuilder() {
      if (resultCase_ == 1) {
         return (com.kroger.domains.person.PersonOuterClass.Person) result_;
      }
      return com.kroger.domains.person.PersonOuterClass.Person.getDefaultInstance();
    }

    public static final int ERROR_FIELD_NUMBER = 2;
    /**
     * <code>.domains.common.Error error = 2;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return resultCase_ == 2;
    }
    /**
     * <code>.domains.common.Error error = 2;</code>
     * @return The error.
     */
    public com.kroger.domains.common.ErrorOuterClass.Error getError() {
      if (resultCase_ == 2) {
         return (com.kroger.domains.common.ErrorOuterClass.Error) result_;
      }
      return com.kroger.domains.common.ErrorOuterClass.Error.getDefaultInstance();
    }
    /**
     * <code>.domains.common.Error error = 2;</code>
     */
    public com.kroger.domains.common.ErrorOuterClass.ErrorOrBuilder getErrorOrBuilder() {
      if (resultCase_ == 2) {
         return (com.kroger.domains.common.ErrorOuterClass.Error) result_;
      }
      return com.kroger.domains.common.ErrorOuterClass.Error.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (resultCase_ == 1) {
        output.writeMessage(1, (com.kroger.domains.person.PersonOuterClass.Person) result_);
      }
      if (resultCase_ == 2) {
        output.writeMessage(2, (com.kroger.domains.common.ErrorOuterClass.Error) result_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (resultCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.kroger.domains.person.PersonOuterClass.Person) result_);
      }
      if (resultCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.kroger.domains.common.ErrorOuterClass.Error) result_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kroger.domains.person.PersonResponseOuterClass.PersonResponse)) {
        return super.equals(obj);
      }
      com.kroger.domains.person.PersonResponseOuterClass.PersonResponse other = (com.kroger.domains.person.PersonResponseOuterClass.PersonResponse) obj;

      if (!getResultCase().equals(other.getResultCase())) return false;
      switch (resultCase_) {
        case 1:
          if (!getPerson()
              .equals(other.getPerson())) return false;
          break;
        case 2:
          if (!getError()
              .equals(other.getError())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (resultCase_) {
        case 1:
          hash = (37 * hash) + PERSON_FIELD_NUMBER;
          hash = (53 * hash) + getPerson().hashCode();
          break;
        case 2:
          hash = (37 * hash) + ERROR_FIELD_NUMBER;
          hash = (53 * hash) + getError().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kroger.domains.person.PersonResponseOuterClass.PersonResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kroger.domains.person.PersonResponseOuterClass.PersonResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kroger.domains.person.PersonResponseOuterClass.PersonResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kroger.domains.person.PersonResponseOuterClass.PersonResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kroger.domains.person.PersonResponseOuterClass.PersonResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kroger.domains.person.PersonResponseOuterClass.PersonResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kroger.domains.person.PersonResponseOuterClass.PersonResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kroger.domains.person.PersonResponseOuterClass.PersonResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kroger.domains.person.PersonResponseOuterClass.PersonResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kroger.domains.person.PersonResponseOuterClass.PersonResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kroger.domains.person.PersonResponseOuterClass.PersonResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kroger.domains.person.PersonResponseOuterClass.PersonResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kroger.domains.person.PersonResponseOuterClass.PersonResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code domains.person.PersonResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:domains.person.PersonResponse)
        com.kroger.domains.person.PersonResponseOuterClass.PersonResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kroger.domains.person.PersonResponseOuterClass.internal_static_domains_person_PersonResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kroger.domains.person.PersonResponseOuterClass.internal_static_domains_person_PersonResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kroger.domains.person.PersonResponseOuterClass.PersonResponse.class, com.kroger.domains.person.PersonResponseOuterClass.PersonResponse.Builder.class);
      }

      // Construct using com.kroger.domains.person.PersonResponseOuterClass.PersonResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        resultCase_ = 0;
        result_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kroger.domains.person.PersonResponseOuterClass.internal_static_domains_person_PersonResponse_descriptor;
      }

      @java.lang.Override
      public com.kroger.domains.person.PersonResponseOuterClass.PersonResponse getDefaultInstanceForType() {
        return com.kroger.domains.person.PersonResponseOuterClass.PersonResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.kroger.domains.person.PersonResponseOuterClass.PersonResponse build() {
        com.kroger.domains.person.PersonResponseOuterClass.PersonResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kroger.domains.person.PersonResponseOuterClass.PersonResponse buildPartial() {
        com.kroger.domains.person.PersonResponseOuterClass.PersonResponse result = new com.kroger.domains.person.PersonResponseOuterClass.PersonResponse(this);
        if (resultCase_ == 1) {
          if (personBuilder_ == null) {
            result.result_ = result_;
          } else {
            result.result_ = personBuilder_.build();
          }
        }
        if (resultCase_ == 2) {
          if (errorBuilder_ == null) {
            result.result_ = result_;
          } else {
            result.result_ = errorBuilder_.build();
          }
        }
        result.resultCase_ = resultCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kroger.domains.person.PersonResponseOuterClass.PersonResponse) {
          return mergeFrom((com.kroger.domains.person.PersonResponseOuterClass.PersonResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kroger.domains.person.PersonResponseOuterClass.PersonResponse other) {
        if (other == com.kroger.domains.person.PersonResponseOuterClass.PersonResponse.getDefaultInstance()) return this;
        switch (other.getResultCase()) {
          case PERSON: {
            mergePerson(other.getPerson());
            break;
          }
          case ERROR: {
            mergeError(other.getError());
            break;
          }
          case RESULT_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kroger.domains.person.PersonResponseOuterClass.PersonResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kroger.domains.person.PersonResponseOuterClass.PersonResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int resultCase_ = 0;
      private java.lang.Object result_;
      public ResultCase
          getResultCase() {
        return ResultCase.forNumber(
            resultCase_);
      }

      public Builder clearResult() {
        resultCase_ = 0;
        result_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          com.kroger.domains.person.PersonOuterClass.Person, com.kroger.domains.person.PersonOuterClass.Person.Builder, com.kroger.domains.person.PersonOuterClass.PersonOrBuilder> personBuilder_;
      /**
       * <code>.domains.person.Person person = 1;</code>
       * @return Whether the person field is set.
       */
      public boolean hasPerson() {
        return resultCase_ == 1;
      }
      /**
       * <code>.domains.person.Person person = 1;</code>
       * @return The person.
       */
      public com.kroger.domains.person.PersonOuterClass.Person getPerson() {
        if (personBuilder_ == null) {
          if (resultCase_ == 1) {
            return (com.kroger.domains.person.PersonOuterClass.Person) result_;
          }
          return com.kroger.domains.person.PersonOuterClass.Person.getDefaultInstance();
        } else {
          if (resultCase_ == 1) {
            return personBuilder_.getMessage();
          }
          return com.kroger.domains.person.PersonOuterClass.Person.getDefaultInstance();
        }
      }
      /**
       * <code>.domains.person.Person person = 1;</code>
       */
      public Builder setPerson(com.kroger.domains.person.PersonOuterClass.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          personBuilder_.setMessage(value);
        }
        resultCase_ = 1;
        return this;
      }
      /**
       * <code>.domains.person.Person person = 1;</code>
       */
      public Builder setPerson(
          com.kroger.domains.person.PersonOuterClass.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          personBuilder_.setMessage(builderForValue.build());
        }
        resultCase_ = 1;
        return this;
      }
      /**
       * <code>.domains.person.Person person = 1;</code>
       */
      public Builder mergePerson(com.kroger.domains.person.PersonOuterClass.Person value) {
        if (personBuilder_ == null) {
          if (resultCase_ == 1 &&
              result_ != com.kroger.domains.person.PersonOuterClass.Person.getDefaultInstance()) {
            result_ = com.kroger.domains.person.PersonOuterClass.Person.newBuilder((com.kroger.domains.person.PersonOuterClass.Person) result_)
                .mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          if (resultCase_ == 1) {
            personBuilder_.mergeFrom(value);
          }
          personBuilder_.setMessage(value);
        }
        resultCase_ = 1;
        return this;
      }
      /**
       * <code>.domains.person.Person person = 1;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          if (resultCase_ == 1) {
            resultCase_ = 0;
            result_ = null;
            onChanged();
          }
        } else {
          if (resultCase_ == 1) {
            resultCase_ = 0;
            result_ = null;
          }
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.domains.person.Person person = 1;</code>
       */
      public com.kroger.domains.person.PersonOuterClass.Person.Builder getPersonBuilder() {
        return getPersonFieldBuilder().getBuilder();
      }
      /**
       * <code>.domains.person.Person person = 1;</code>
       */
      public com.kroger.domains.person.PersonOuterClass.PersonOrBuilder getPersonOrBuilder() {
        if ((resultCase_ == 1) && (personBuilder_ != null)) {
          return personBuilder_.getMessageOrBuilder();
        } else {
          if (resultCase_ == 1) {
            return (com.kroger.domains.person.PersonOuterClass.Person) result_;
          }
          return com.kroger.domains.person.PersonOuterClass.Person.getDefaultInstance();
        }
      }
      /**
       * <code>.domains.person.Person person = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kroger.domains.person.PersonOuterClass.Person, com.kroger.domains.person.PersonOuterClass.Person.Builder, com.kroger.domains.person.PersonOuterClass.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          if (!(resultCase_ == 1)) {
            result_ = com.kroger.domains.person.PersonOuterClass.Person.getDefaultInstance();
          }
          personBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.kroger.domains.person.PersonOuterClass.Person, com.kroger.domains.person.PersonOuterClass.Person.Builder, com.kroger.domains.person.PersonOuterClass.PersonOrBuilder>(
                  (com.kroger.domains.person.PersonOuterClass.Person) result_,
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        resultCase_ = 1;
        onChanged();;
        return personBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.kroger.domains.common.ErrorOuterClass.Error, com.kroger.domains.common.ErrorOuterClass.Error.Builder, com.kroger.domains.common.ErrorOuterClass.ErrorOrBuilder> errorBuilder_;
      /**
       * <code>.domains.common.Error error = 2;</code>
       * @return Whether the error field is set.
       */
      public boolean hasError() {
        return resultCase_ == 2;
      }
      /**
       * <code>.domains.common.Error error = 2;</code>
       * @return The error.
       */
      public com.kroger.domains.common.ErrorOuterClass.Error getError() {
        if (errorBuilder_ == null) {
          if (resultCase_ == 2) {
            return (com.kroger.domains.common.ErrorOuterClass.Error) result_;
          }
          return com.kroger.domains.common.ErrorOuterClass.Error.getDefaultInstance();
        } else {
          if (resultCase_ == 2) {
            return errorBuilder_.getMessage();
          }
          return com.kroger.domains.common.ErrorOuterClass.Error.getDefaultInstance();
        }
      }
      /**
       * <code>.domains.common.Error error = 2;</code>
       */
      public Builder setError(com.kroger.domains.common.ErrorOuterClass.Error value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          errorBuilder_.setMessage(value);
        }
        resultCase_ = 2;
        return this;
      }
      /**
       * <code>.domains.common.Error error = 2;</code>
       */
      public Builder setError(
          com.kroger.domains.common.ErrorOuterClass.Error.Builder builderForValue) {
        if (errorBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }
        resultCase_ = 2;
        return this;
      }
      /**
       * <code>.domains.common.Error error = 2;</code>
       */
      public Builder mergeError(com.kroger.domains.common.ErrorOuterClass.Error value) {
        if (errorBuilder_ == null) {
          if (resultCase_ == 2 &&
              result_ != com.kroger.domains.common.ErrorOuterClass.Error.getDefaultInstance()) {
            result_ = com.kroger.domains.common.ErrorOuterClass.Error.newBuilder((com.kroger.domains.common.ErrorOuterClass.Error) result_)
                .mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          if (resultCase_ == 2) {
            errorBuilder_.mergeFrom(value);
          }
          errorBuilder_.setMessage(value);
        }
        resultCase_ = 2;
        return this;
      }
      /**
       * <code>.domains.common.Error error = 2;</code>
       */
      public Builder clearError() {
        if (errorBuilder_ == null) {
          if (resultCase_ == 2) {
            resultCase_ = 0;
            result_ = null;
            onChanged();
          }
        } else {
          if (resultCase_ == 2) {
            resultCase_ = 0;
            result_ = null;
          }
          errorBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.domains.common.Error error = 2;</code>
       */
      public com.kroger.domains.common.ErrorOuterClass.Error.Builder getErrorBuilder() {
        return getErrorFieldBuilder().getBuilder();
      }
      /**
       * <code>.domains.common.Error error = 2;</code>
       */
      public com.kroger.domains.common.ErrorOuterClass.ErrorOrBuilder getErrorOrBuilder() {
        if ((resultCase_ == 2) && (errorBuilder_ != null)) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          if (resultCase_ == 2) {
            return (com.kroger.domains.common.ErrorOuterClass.Error) result_;
          }
          return com.kroger.domains.common.ErrorOuterClass.Error.getDefaultInstance();
        }
      }
      /**
       * <code>.domains.common.Error error = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.kroger.domains.common.ErrorOuterClass.Error, com.kroger.domains.common.ErrorOuterClass.Error.Builder, com.kroger.domains.common.ErrorOuterClass.ErrorOrBuilder> 
          getErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          if (!(resultCase_ == 2)) {
            result_ = com.kroger.domains.common.ErrorOuterClass.Error.getDefaultInstance();
          }
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.kroger.domains.common.ErrorOuterClass.Error, com.kroger.domains.common.ErrorOuterClass.Error.Builder, com.kroger.domains.common.ErrorOuterClass.ErrorOrBuilder>(
                  (com.kroger.domains.common.ErrorOuterClass.Error) result_,
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        resultCase_ = 2;
        onChanged();;
        return errorBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:domains.person.PersonResponse)
    }

    // @@protoc_insertion_point(class_scope:domains.person.PersonResponse)
    private static final com.kroger.domains.person.PersonResponseOuterClass.PersonResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kroger.domains.person.PersonResponseOuterClass.PersonResponse();
    }

    public static com.kroger.domains.person.PersonResponseOuterClass.PersonResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PersonResponse>
        PARSER = new com.google.protobuf.AbstractParser<PersonResponse>() {
      @java.lang.Override
      public PersonResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PersonResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PersonResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PersonResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kroger.domains.person.PersonResponseOuterClass.PersonResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_domains_person_PersonResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_domains_person_PersonResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$domains/person/person_response.proto\022\016" +
      "domains.person\032\033domains/person/person.pr" +
      "oto\032\032domains/common/error.proto\"l\n\016Perso" +
      "nResponse\022(\n\006person\030\001 \001(\0132\026.domains.pers" +
      "on.PersonH\000\022&\n\005error\030\002 \001(\0132\025.domains.com" +
      "mon.ErrorH\000B\010\n\006resultB\033\n\031com.kroger.doma" +
      "ins.personb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kroger.domains.person.PersonOuterClass.getDescriptor(),
          com.kroger.domains.common.ErrorOuterClass.getDescriptor(),
        });
    internal_static_domains_person_PersonResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_domains_person_PersonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_domains_person_PersonResponse_descriptor,
        new java.lang.String[] { "Person", "Error", "Result", });
    com.kroger.domains.person.PersonOuterClass.getDescriptor();
    com.kroger.domains.common.ErrorOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
