// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domains/person/phone_number.proto

package com.kroger.domains.person;

public final class PhoneNumberOuterClass {
  private PhoneNumberOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PhoneNumberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:domains.person.PhoneNumber)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.domains.person.PhoneType phone_type = 1;</code>
     * @return The enum numeric value on the wire for phoneType.
     */
    int getPhoneTypeValue();
    /**
     * <code>.domains.person.PhoneType phone_type = 1;</code>
     * @return The phoneType.
     */
    com.kroger.domains.person.PhoneTypeOuterClass.PhoneType getPhoneType();

    /**
     * <code>string number = 2;</code>
     * @return The number.
     */
    java.lang.String getNumber();
    /**
     * <code>string number = 2;</code>
     * @return The bytes for number.
     */
    com.google.protobuf.ByteString
        getNumberBytes();
  }
  /**
   * Protobuf type {@code domains.person.PhoneNumber}
   */
  public  static final class PhoneNumber extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:domains.person.PhoneNumber)
      PhoneNumberOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PhoneNumber.newBuilder() to construct.
    private PhoneNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PhoneNumber() {
      phoneType_ = 0;
      number_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PhoneNumber();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PhoneNumber(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              phoneType_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              number_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kroger.domains.person.PhoneNumberOuterClass.internal_static_domains_person_PhoneNumber_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kroger.domains.person.PhoneNumberOuterClass.internal_static_domains_person_PhoneNumber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.class, com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.Builder.class);
    }

    public static final int PHONE_TYPE_FIELD_NUMBER = 1;
    private int phoneType_;
    /**
     * <code>.domains.person.PhoneType phone_type = 1;</code>
     * @return The enum numeric value on the wire for phoneType.
     */
    public int getPhoneTypeValue() {
      return phoneType_;
    }
    /**
     * <code>.domains.person.PhoneType phone_type = 1;</code>
     * @return The phoneType.
     */
    public com.kroger.domains.person.PhoneTypeOuterClass.PhoneType getPhoneType() {
      @SuppressWarnings("deprecation")
      com.kroger.domains.person.PhoneTypeOuterClass.PhoneType result = com.kroger.domains.person.PhoneTypeOuterClass.PhoneType.valueOf(phoneType_);
      return result == null ? com.kroger.domains.person.PhoneTypeOuterClass.PhoneType.UNRECOGNIZED : result;
    }

    public static final int NUMBER_FIELD_NUMBER = 2;
    private volatile java.lang.Object number_;
    /**
     * <code>string number = 2;</code>
     * @return The number.
     */
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      }
    }
    /**
     * <code>string number = 2;</code>
     * @return The bytes for number.
     */
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (phoneType_ != com.kroger.domains.person.PhoneTypeOuterClass.PhoneType.MOBILE.getNumber()) {
        output.writeEnum(1, phoneType_);
      }
      if (!getNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, number_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (phoneType_ != com.kroger.domains.person.PhoneTypeOuterClass.PhoneType.MOBILE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, phoneType_);
      }
      if (!getNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, number_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber)) {
        return super.equals(obj);
      }
      com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber other = (com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber) obj;

      if (phoneType_ != other.phoneType_) return false;
      if (!getNumber()
          .equals(other.getNumber())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PHONE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + phoneType_;
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code domains.person.PhoneNumber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:domains.person.PhoneNumber)
        com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kroger.domains.person.PhoneNumberOuterClass.internal_static_domains_person_PhoneNumber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kroger.domains.person.PhoneNumberOuterClass.internal_static_domains_person_PhoneNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.class, com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.Builder.class);
      }

      // Construct using com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        phoneType_ = 0;

        number_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kroger.domains.person.PhoneNumberOuterClass.internal_static_domains_person_PhoneNumber_descriptor;
      }

      @java.lang.Override
      public com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber getDefaultInstanceForType() {
        return com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.getDefaultInstance();
      }

      @java.lang.Override
      public com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber build() {
        com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber buildPartial() {
        com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber result = new com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber(this);
        result.phoneType_ = phoneType_;
        result.number_ = number_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber) {
          return mergeFrom((com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber other) {
        if (other == com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber.getDefaultInstance()) return this;
        if (other.phoneType_ != 0) {
          setPhoneTypeValue(other.getPhoneTypeValue());
        }
        if (!other.getNumber().isEmpty()) {
          number_ = other.number_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int phoneType_ = 0;
      /**
       * <code>.domains.person.PhoneType phone_type = 1;</code>
       * @return The enum numeric value on the wire for phoneType.
       */
      public int getPhoneTypeValue() {
        return phoneType_;
      }
      /**
       * <code>.domains.person.PhoneType phone_type = 1;</code>
       * @param value The enum numeric value on the wire for phoneType to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneTypeValue(int value) {
        phoneType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.domains.person.PhoneType phone_type = 1;</code>
       * @return The phoneType.
       */
      public com.kroger.domains.person.PhoneTypeOuterClass.PhoneType getPhoneType() {
        @SuppressWarnings("deprecation")
        com.kroger.domains.person.PhoneTypeOuterClass.PhoneType result = com.kroger.domains.person.PhoneTypeOuterClass.PhoneType.valueOf(phoneType_);
        return result == null ? com.kroger.domains.person.PhoneTypeOuterClass.PhoneType.UNRECOGNIZED : result;
      }
      /**
       * <code>.domains.person.PhoneType phone_type = 1;</code>
       * @param value The phoneType to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneType(com.kroger.domains.person.PhoneTypeOuterClass.PhoneType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        phoneType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.domains.person.PhoneType phone_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhoneType() {
        
        phoneType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object number_ = "";
      /**
       * <code>string number = 2;</code>
       * @return The number.
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string number = 2;</code>
       * @return The bytes for number.
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string number = 2;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string number = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        
        number_ = getDefaultInstance().getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string number = 2;</code>
       * @param value The bytes for number to set.
       * @return This builder for chaining.
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        number_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:domains.person.PhoneNumber)
    }

    // @@protoc_insertion_point(class_scope:domains.person.PhoneNumber)
    private static final com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber();
    }

    public static com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PhoneNumber>
        PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
      @java.lang.Override
      public PhoneNumber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PhoneNumber(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PhoneNumber> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kroger.domains.person.PhoneNumberOuterClass.PhoneNumber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_domains_person_PhoneNumber_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_domains_person_PhoneNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!domains/person/phone_number.proto\022\016dom" +
      "ains.person\032\037domains/person/phone_type.p" +
      "roto\"L\n\013PhoneNumber\022-\n\nphone_type\030\001 \001(\0162" +
      "\031.domains.person.PhoneType\022\016\n\006number\030\002 \001" +
      "(\tB\033\n\031com.kroger.domains.personb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kroger.domains.person.PhoneTypeOuterClass.getDescriptor(),
        });
    internal_static_domains_person_PhoneNumber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_domains_person_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_domains_person_PhoneNumber_descriptor,
        new java.lang.String[] { "PhoneType", "Number", });
    com.kroger.domains.person.PhoneTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
