// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/person/person.service.proto

package com.kroger.services.person;

public final class PersonServiceOuterClass {
  private PersonServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$services/person/person.service.proto\022\017" +
      "services.person\032#domains/person/person_r" +
      "equest.proto\032$domains/person/person_resp" +
      "onse.proto2]\n\rPersonService\022L\n\tFetchById" +
      "\022\035.domains.person.PersonRequest\032\036.domain" +
      "s.person.PersonResponse\"\000B\034\n\032com.kroger." +
      "services.personb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kroger.domains.person.PersonRequestOuterClass.getDescriptor(),
          com.kroger.domains.person.PersonResponseOuterClass.getDescriptor(),
        });
    com.kroger.domains.person.PersonRequestOuterClass.getDescriptor();
    com.kroger.domains.person.PersonResponseOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
