// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domains/common/error.proto

package com.thougtworks.domains.common;

public final class ErrorOuterClass {
  private ErrorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_domains_common_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_domains_common_Error_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032domains/common/error.proto\022\016domains.co" +
      "mmon\"%\n\005Error\022\014\n\004code\030\001 \001(\005\022\016\n\006reason\030\002 " +
      "\001(\tB\"\n\036com.thougtworks.domains.commonP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_domains_common_Error_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_domains_common_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_domains_common_Error_descriptor,
        new java.lang.String[] { "Code", "Reason", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
