// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domains/common/error.proto

package com.thougtworks.domains.common;

public interface ErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:domains.common.Error)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string reason = 2;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 2;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
